version: 2
project_name: dotman
before:
  hooks: [go mod tidy, go vet ./..., go test ./... -count=1 -timeout 30s]
builds:
  - {id: dotman, main: ., binary: dotman, env: [CGO_ENABLED=0], goos: [linux, android, darwin], goarch: [amd64, arm64], ignore: [{goos: android, goarch: amd64}], ldflags: [-s -w -X main.version={{.Version}}], flags: [-trimpath]}
archives: [{id: binaries, builds: [dotman], name_template: "dotman-{{ .Os }}-{{ .Arch }}", format: binary}]
checksum: {name_template: "checksums.txt"}
